import { CorporationResponse } from "./home/interfaces/CorporationResponse";

export const corporationsArray: CorporationResponse[]  = [
      {
        id: "1", 
        name: "Centro De Atendimento Psicossocial", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Avenida Getúlio Vargas - 1527",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "3366-1993",
      },
      {
        id: "primeiro", 
        name: "Policlínica", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Logo ali",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "3366-0000",
      },
      {
        id: "primeiro", 
        name: "Unidade Básica de Saúde Santos Dumont", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Rua Elite - Bairro Santos Dumont",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "3366-3529",
      },
      {
        id: "primeiro", 
        name: "Unidade Básica de Saúde Santa Filomena", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Rua Justiniano Borba - Bairro Santa Filomena",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "3366-3551",
      },
      {
        id: "primeiro", 
        name: "Unidade Básica de Saúde Alaides Nunes de Amaral", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: " Avenida Salomão Tomas de Matos - Bairro Universitário",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "0000-0000",
      },
      {
        id: "primeiro", 
        name: "Unidade Básica de Saúde Raimundo Bela", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Rua 05 - Bairro Novo Horizonte",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "0000-0000",
      },
      {
        id: "primeiro", 
        name: "Unidade Básica de Saúde Odicilia Lino Pereira", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Avenida Umberto Sardinha Sobrinho",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "0000-0000",
      },
      {
        id: "primeiro", 
        name: "Unidade Básica de Saúde Correntinho", 
        category: "Saude", 
        description: "Centro de atendimento médico",
        adress: "Avenida Getúlio Vargas - Bairro Correntinho",
        hours: "Dás 08:00 as 18:00",
        phoneNumber: "3366-1456",
      },
    ]