spring.application.name=mirahelp
server.port=${PORT}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${URL_MYSQL_DB}
spring.datasource.username=${USERNAME_MYSQL_DB}
spring.datasource.password=${PASSWORD_MYSQL_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver